services:
  selenium-hub:
    image: selenium/hub:4.11.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:4444/status | grep -q '\"ready\": true'"]
      interval: 5s
      timeout: 5s
      retries: 12

  chrome:
    image: selenium/node-chrome:4.11.0
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    depends_on:
      - selenium-hub

  firefox:
    image: selenium/node-firefox:4.11.0
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    depends_on:
      - selenium-hub

  scraper:
    build: .
    volumes:
      - .:/app
    depends_on:
      selenium-hub:
        condition: service_healthy
      chrome:
        condition: service_started
      firefox:
        condition: service_started
    environment:
      - SELENIUM_HUB_URL=http://selenium-hub:4444